var srcIndex = new Map(JSON.parse('[\
["bitflags",["",[],["lib.rs"]]],\
["byteorder",["",[],["io.rs","lib.rs"]]],\
["crc_any",["",[["constants",[],["crc_u16.rs","crc_u32.rs","crc_u64.rs","crc_u8.rs","mod.rs"]]],["crc_u16.rs","crc_u32.rs","crc_u64.rs","crc_u8.rs","lib.rs","lookup_table.rs"]]],\
["ioctl_rs",["",[["os",[],["linux.rs","mod.rs"]]],["lib.rs"]]],\
["lazy_static",["",[],["inline_lazy.rs","lib.rs"]]],\
["libc",["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]]],\
["mavlink",["",[],["lib.rs"]]],\
["mavlink_bindgen",["",[],["binder.rs","error.rs","lib.rs","parser.rs","util.rs"]]],\
["mavlink_core",["",[["connection",[],["direct_serial.rs","file.rs","mod.rs","tcp.rs","udp.rs"]]],["bytes.rs","bytes_mut.rs","error.rs","lib.rs","peek_reader.rs","utils.rs"]]],\
["memchr",["",[["arch",[["all",[["packedpair",[],["default_rank.rs","mod.rs"]]],["memchr.rs","mod.rs","rabinkarp.rs","shiftor.rs","twoway.rs"]],["generic",[],["memchr.rs","mod.rs","packedpair.rs"]],["x86_64",[["avx2",[],["memchr.rs","mod.rs","packedpair.rs"]],["sse2",[],["memchr.rs","mod.rs","packedpair.rs"]]],["memchr.rs","mod.rs"]]],["mod.rs"]],["memmem",[],["mod.rs","searcher.rs"]]],["cow.rs","ext.rs","lib.rs","macros.rs","memchr.rs","vector.rs"]]],\
["num_derive",["",[],["lib.rs","test.rs"]]],\
["num_traits",["",[["ops",[],["bytes.rs","checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","sign.rs"]]],\
["proc_macro2",["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]]],\
["quick_xml",["",[["events",[],["attributes.rs","mod.rs"]],["reader",[],["buffered_reader.rs","mod.rs","ns_reader.rs","parser.rs","slice_reader.rs"]]],["encoding.rs","errors.rs","escapei.rs","lib.rs","name.rs","utils.rs","writer.rs"]]],\
["quote",["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]]],\
["serde",["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","size_hint.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]]],\
["serde_arrays",["",[],["lib.rs"]]],\
["serde_derive",["",[["internals",[],["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]]],["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","this.rs"]]],\
["serial",["",[],["lib.rs"]]],\
["serial_core",["",[],["lib.rs"]]],\
["serial_unix",["",[],["error.rs","lib.rs","poll.rs","tty.rs"]]],\
["termios",["",[["os",[],["linux.rs","mod.rs"]]],["ffi.rs","lib.rs"]]],\
["thiserror",["",[],["aserror.rs","display.rs","lib.rs"]]],\
["thiserror_impl",["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","span.rs","valid.rs"]]],\
["unicode_ident",["",[],["lib.rs","tables.rs"]]]\
]'));
createSrcSidebar();
