//! MAVLink dialect Rust bindings generated by mavlink-bindgen.
//!
//! Enable a dialect by enabling its Cargo feature:
//! - dialect-ardupilotmega
//! - dialect-asluav
//! - dialect-avssuas
//! - dialect-common
//! - dialect-csairlink
//! - dialect-cubepilot
//! - dialect-development
//! - dialect-dynamic
//! - dialect-icarous
//! - dialect-loweheiser
//! - dialect-marsh
//! - dialect-matrixpilot
//! - dialect-minimal
//! - dialect-paparazzi
//! - dialect-python_array_test
//! - dialect-standard
//! - dialect-stemstudios
//! - dialect-storm32
//! - dialect-test
//! - dialect-ualberta
//! - dialect-uavionix

include!(concat!(env!("OUT_DIR"), "/mod.rs"));

#[cfg(feature = "dialect-dynamic")]
#[cfg_attr(docsrs, doc(cfg(feature = "dialect-dynamic")))]
pub mod dynamic;
